site_name: Zachary Lui
site_url: https://zacharylui.ca/

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.instant

nav:
  - Home: index.md
  - Acupuncture for Anxiety: anxiety.md
  - Marriage Officiant: officiant.md

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - md_in_html