site_name: Zachary Lui

theme:
  name: material
  palette:
    scheme: slate
    primary: black
    accent: amber

  font:
    text: Inter
    code: Roboto Mono

  features:
    - navigation.instant
    - navigation.tabs
    - navigation.sections
    - content.code.copy

nav:
  - Home: index.md
  - Acupuncture for Anxiety: anxiety.md
  - Marriage Officiant: officiant.md
  - Writing: writing.md
 

extra_css:
  - stylesheets/extra.css